version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: notes_app_development
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Notes-App
    ports:
      - "3000:3000"
    depends_on:
      - db