default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: admin

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: notes_app_development
  username: admin
  password: admin
  host: localhost
  # The specified database role being used to connect to PostgreSQL.
  # To create additional roles in PostgreSQL see `$ createuser --help`.
  # When left blank, PostgreSQL will use the default role. This is
  # the same name as the operating system user running Rails.
  #username: notes_app

test:
  <<: *default
  database: notes_app_test

production:
  <<: *default
  database: notes_app_production
  username: notes_app
  password: <%= ENV["NOTES_APP_DATABASE_PASSWORD"] %>
