default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: admin

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: notes_app_development
  username: admin
  password: admin
  host: db

test:
  <<: *default
  database: notes_app_test

production:
  <<: *default
  database: notes_app_production
  username: notes_app
  password: <%= ENV["NOTES_APP_DATABASE_PASSWORD"] %>
